### ISSUE TITLE
Update to Java 17 or 21?

### ISSUE THREAD

**Issue by electrum** [dylibso/chicory#273]
Newer Java language features such as records, pattern matching, sealed classes, etc., improve the developer experience. What do we think about updating Chicory to a newer Java version?

**Comment by andreaTP** [comment]
Thanks for this question @electrum , we are constantly re-evaluating our position on this subject.
So far we have been pretty conservative over the Java version to make sure that this project can be embedded even in legacy codebases.
Another aspect of it is the fact that we know this codebase runs on Android.

That said, I would be open to re-evaluate when we have compelling reasons.

**Comment by bhelx** [comment]
As mentioned in #295 , we're trying to stay widely compatible at the moment and we're not ready to upgrade the Java version just yet. I do think we can revisit this next year, and in the meantime we're happy to discuss any individual problems that might be associated regarding compatibility with newer javas.
