### ISSUE TITLE
Stack unwinds incorrectly  when jumping from `if` block to the outermost block using a `br_if`

### ISSUE THREAD

**Issue by illarionov** [dylibso/chicory#294]
Given the following code:

```wat
(module
  (type $t0 (func (param i32) (result i32)))

  (func $innerFunc (type $t0) (param $arg0 i32) (result i32)
    (local $resultCode i32)
    block $outerBlock
      i32.const -1 ;; These values must be dropped from the stack
      i32.const -2 ;; when the br_if jump is triggered

      i32.const -3
      if (result i32)
        local.get $arg0
        local.tee $resultCode
        br_if $outerBlock
        i32.const 100
      else
        i32.const 200
      end
      local.set $resultCode

      drop
      drop
    end
    local.get $resultCode)

  (func $main (export "main") (type $t0) (param $arg0 i32) (result i32)
    i32.const 0
    local.get $arg0
    call $innerFunc
    i32.add)

  (memory $M0 1))
```

When executing 'main' on Chicory with the argument '5', the function returns the incorrect result of 3.
In the "innerFunc", the  `br_if` jump  to the outer block is triggered and after its execution the values -1 and -2 remain on the stack:
```
stack = {ArrayDeque@2296}  size = 4
 0 = {Value@2311} "5@i32"
 1 = {Value@2312} "-2@i32"
 2 = {Value@2313} "-1@i32"
 3 = {Value@2314} "0@i32"
```

When executed on `wasm-interp` the result is correct:
```shell
$ wasm-interp test.wasm -r "main" -a "i32:5"
main(i32:5) => i32:5
```

**Comment by andreaTP** [comment]
Thanks a lot @illarionov for the detailed report and the minimal reproducer!
Are you willing to look into this issue?

Also @mariofusco might be interested :slightly_smiling_face:

**Comment by illarionov** [comment]
I've been trying to look into this, but I think this issue should be looked up by someone who originally implemented the control flow instructions in the project or know how they should work.

**Comment by andreaTP** [comment]
Thanks for getting back, I'm a bit busy but I'll try to have a look by the end of the week.

**Comment by andreaTP** [comment]
Finally managed to get to this, sorry for the delay!

**Comment by illarionov** [comment]
NP, Thank you for the quick resolution!

**Comment by illarionov** [comment]
Thank you once again for the fix. I checked the changes in #301 and found that the problem with `br_if` has been resolved. However, I quickly ran into a similar issue with the `br` and `br_table` instructions. Perhaps these instructions should also be marked as control frames.
It can be reproduced using the following examples:

##### `br`

```wasm
(module
  (func $main (export "main") (result i32)
    i32.const 1
    i32.const 3
    block $outerBlock
      i32.const 5
      i32.const 7
      if
        br $outerBlock
      end
      drop
    end
    i32.add))
```

##### `br_table`

```wasm
(module
  (func $main (export "main") (result i32)
    i32.const 1
    i32.const 3
    block $outerBlock
      i32.const 5
      i32.const 7
      if
        i32.const 0
        br_table $outerBlock
      end
      drop
    end
    i32.add))
```

**Comment by andreaTP** [comment]
Thanks for the update @illarionov , I updated my PR to take into account the additional cases reported.
Thanks a lot for the help and the great reproducers!
