### ISSUE TITLE
AOT tidy-up

### ISSUE THREAD

**Issue by danielperano** [dylibso/chicory#331]
As per our Zulip conversation, I merged #312 as-is. I'm creating this issue to track the tidy-up that @andreaTP suggested.

**Comment by danielperano** [comment]
Running Spotless on this just moves the star import to the top - my guess is that Spotless allows the star import because it's bringing in so many constants. Personally I prefer this over listing them all out and since Spotless allows it (with the current config) I'd prefer to leave it.

**Comment by andreaTP** [comment]
Completed by: #332 and #333
