### ISSUE TITLE
Exception passthrough

### ISSUE THREAD

**Issue by SoniEx2** [dylibso/chicory#338]
It would be nice to have some way to pass (most) exceptions through, instead of having them wrapped in `WASMMachineException`.

In particular because `WASMMachineException` is extremely slow for the things [this little special constructor](https://docs.oracle.com/javase/8/docs/api/java/lang/RuntimeException.html#RuntimeException-java.lang.String-java.lang.Throwable-boolean-boolean- "RuntimeException(String, Throwable, boolean, boolean)") enables one to do. The specific pattern is usually called "non-local control flow".

Granted, one can still use `Error` for this purpose, since `Error` has similar semantics to `RuntimeException` and also includes the appropriate constructor. [And using `Error` for "normal occurrences" isn't completely unheard of.](https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadDeath.html "ThreadDeath")

**Comment by andreaTP** [comment]
Thanks for opening this issue!

> The specific pattern is usually called "non-local control flow".

I have a few questions/doubts about enabling this functionality, at this stage of the project.

If you are able to share a concrete use case(although slow) it will be great, so that we can continue the discussion being sure we are on the same page.

**Comment by SoniEx2** [comment]
Sure! Running pre-EH emscripten modules that make use of setjmp/longjmp, for starters. (Does chicory even support wasm EH at this point?) This includes things such as Lua.

**Comment by andreaTP** [comment]
> Does chicory even support wasm EH at this point?

Not yet, if I understand it correctly we can evaluate this request after we have a more solid exception handling story.

**Comment by SoniEx2** [comment]
Yes, the pre-EH system exists for runtimes that don't support EH, like Chicory. Except it doesn't work with Chicory properly. Unless you implement it on top of `Error`.

**Comment by andreaTP** [comment]
Tentatively closing this issue as fixed in: #459 
Please feel free to re-open or open a new Issue if I missed some context.

**Comment by SoniEx2** [comment]
that looks great, thanks!
