### ISSUE TITLE
Validate interpreter handling of stack unwinds

### ISSUE THREAD

**Issue by electrum** [dylibso/chicory#401]
While debugging `fac-ssa` from `fac.wast`, I noticed that the stack continues to grow. It appears that the interpreter is not removing the initial loop parameters when unwinding. We could validate that the stack is empty when the function returns.

**Comment by andreaTP** [comment]
Started debugging this issue [here](https://github.com/dylibso/chicory/compare/main...andreaTP:chicory:issue401?expand=1), would love any help on this subject.

So far, the only thing I'm convinced is that the `if (currentInstruction.depth() > 0)` in `StackFrame` are likely incorrect.
More, the `instruction.scope` of `LOOP` is it's `END`.
