### ISSUE TITLE
Wasm version

### ISSUE THREAD

**Issue by ablax** [dylibso/chicory#437]
Latest published wasm version is 0.0.10 opposed to most of the packages being 0.0.11

**Comment by bhelx** [comment]
It seems 0.0.11 failed to fully deploy. please use 0.0.10 for the moment. We will fix.

**Comment by bhelx** [comment]
Since there was a large gap of changes from 10 to 11, instead of waiting I've released version 0.0.12. Give it some time to propagate. Will check back and re-open if it's still not working by tonight.

**Comment by bhelx** [comment]
Seems to be out already. Please let me know if bumping to 0.0.12 doesn't fix for you @ablax
