### ISSUE TITLE
Initial benchmark setup

### ISSUE THREAD

**Issue by thomasdarimont** [dylibso/chicory#52]
It is advisable to have solid benchmarks from the beginning to quickly and easily assess the performance impact of different implementations.

For this we could leverage [jmh](https://github.com/openjdk/jmh). 
Some example JMH integrations can be found here: https://github.com/FasterXML/jackson-benchmarks/tree/2.15

The idea of this issue is to provide an initial setup to enable the project to write easy and reliable micro benchmarks.

**Comment by bhelx** [comment]
I started a branch for this this morning. We've been mostly using the tests to measure performance but i think it makes more sense to get a basic micro benchmark setup working. JMH will provide more control and also i'd like to separate out things like parsing, compilation, and runtime performance. Will ping you when i get a PR started @danielperano

**Comment by thomasdarimont** [comment]
I think this has been solved by https://github.com/dylibso/chicory/pull/280 in the meantime.
