### ISSUE TITLE
Clean Parser API

### ISSUE THREAD

**Issue by andreaTP** [dylibso/chicory#521]
The current `Parser` API consist of the expected `parse` methods and some `read...` methods.
I think the `read...` methods should not be public (at least not available from the `Parser` class).

**Comment by andreaTP** [comment]
an alternative would be to move the `parse` methods to `Module`

**Comment by evacchi** [comment]
it looks like the following `read()` methods are public because they are used in `NameCustomSection#parse()`

```
readVarUInt32
readName
readName
```

**Comment by electrum** [comment]
Given that the parser is intended to support custom sections, we need the public utility methods available somewhere for use by user code. Maybe a new `Parsing` utility class?
