### ISSUE TITLE
Down-level logging in the WasiPreview1 module

### ISSUE THREAD

**Issue by bhelx** [dylibso/chicory#534]
https://github.com/dylibso/chicory/blob/b69237737c6f05f74d4c3fafbb1e32a350953e9a/wasi/src/main/java/com/dylibso/chicory/wasi/WasiPreview1.java#L161

I think it would be appropriate to set the log level on all of these to trace or at most debug. It can be quite noisy for the average user.

**Comment by andreaTP** [comment]
I agree, `trace` sounds appropriate to me.
