### ISSUE TITLE
Cloudflare failure

### ISSUE THREAD

**Issue by andreaTP** [dylibso/chicory#580]
The build of the docs in Cloudflare failed on `main`, but I'm unable to access the logs to try to fix it :sweat: 

The failure is here: https://github.com/dylibso/chicory/runs/31630153048

**Comment by andreaTP** [comment]
I can, but, after thinking about it,
the ideal solution would be to have a yarn.lock that will not be modified I guess, to have more reproducible builds ...

Not sure why it differs on Cloudflare though...

**Comment by bhelx** [comment]
I'll give it a try. not sure how it got out of sync and why cloudflare keeps building a different version of it.

**Comment by bhelx** [comment]
Give this a try. I'm still kind of wary about using yarn as it might just lead to more hours wasted: https://github.com/dylibso/chicory/pull/581
