### ISSUE TITLE
Implement `poll_oneoff` in WASI P1

### ISSUE THREAD

**Issue by andreaTP** [dylibso/chicory#592]
Zig, the Go standard library, Rust(in some cases) and c2w require `poll_oneoff`.
It would be great to have a stable implementation of it.

Spike ref:
https://github.com/dylibso/chicory/pull/530/files#diff-9037d84891e8043e756bfd63e2101686b67d1cad2cc2c4af3b2e6b48675acdf3R1086

**Comment by electrum** [comment]
I started looking at this a while ago, but it didn't seem possible to run the WASI testsuite tests due to them using stdin/stdout/stderr which are fundamentally blocking in our implementation as we use `InputStream`/`OutputStream`. Would it suffice to simply implement the timer part and return `ENOTSUP` for other descriptors?

**Comment by electrum** [comment]
I found that various library functions in Python such as the `socket` library will fail due to `poll_oneoff` (even though they would eventually fail with a different error as WASI doesn't support creating sockets).

**Comment by evacchi** [comment]
> Would it suffice to simply implement the timer part and return `ENOTSUP` for other descriptors?

pretty much. Also, stdin kinda wants to be treated differently, so in wazero we special case that. Basically I've been meaning to port over the logic here https://github.com/tetratelabs/wazero/blob/610c202ec48f3a7c729f2bf11707330127ab3689/imports/wasi_snapshot_preview1/poll.go#L98-L197

**Comment by andreaTP** [comment]
> Would it suffice to simply implement the timer part and return ENOTSUP for other descriptors?

Very likely, from what I've seen the Go and Zig code using it are fine with the timer part, just remember to throw meaningful exceptions in case is not so that we can eventually track other usages.

**Comment by electrum** [comment]
That code is polling for data on stdin. We could do a sleep loop while calling `available()`.

**Comment by evacchi** [comment]
that might work
