### ISSUE TITLE
MemoryLimits: allow to impose constraints to an instance

### ISSUE THREAD

**Issue by evacchi** [dylibso/chicory#606]
Modules are able to define their own memory constraints, but one useful feature of Wasm engines is to allow the host to control the use of resources of the guests.

We should allow end-users to refine the memory constraints of a Wasm module so that 
1) we can impose finer restrictions on modules that have been compiled with default values (i.e. unrestricted limits)
2) rogue instances cannot grow their memory indefinitely

- One solution could be to provide a `.withMemoryLimits()` on the `InstanceBuilder`.
- Another, more general solution would be to provide `.withMemoryFactory()` for other use cases (e.g. experiment with alternative allocation strategies, such as off-heap/MemorySegment)
In this case, however, it would be also useful to define a specific, built-in factory that allows to easily constrain memory limits; e.g. `.withMemoryFactory(MemoryLimits.of(...))`

**Comment by andreaTP** [comment]
I'm in favor of `.withMemoryFactory()` :+1: as it also covers the possibility of experimenting with new JVM features and offheap memory.

**Comment by evacchi** [comment]
updated the top post with a reference to off-heap 👍

**Comment by electrum** [comment]
I think these are complementary features. The `MemoryFactory` interface would accept `MemoryLimits`. We shouldn't mix the allocation or access strategy with memory limits.

**Comment by electrum** [comment]
Related, I noticed that `Instance.Builder#validateHostMemoryType` allows `MemoryLimits.MAX_PAGES` (65536) and converts that to `Memory.RUNTIME_MAX_PAGES` (32767). But any intermediate value would fail. Is this the intended behavior?

**Comment by evacchi** [comment]
1. TBH I'm in favor of separating the two concepts. 
2. re: `Memory.RUNTIME_MAX_PAGES` I don't think that's intended...
