### ISSUE TITLE
Docs don't match latest release

### ISSUE THREAD

**Issue by abelsromero** [dylibso/chicory#634]
I wanted to play with the project, and it seems to me the docs are built from the latest commit which contains classes and methods that are not yet available in the latest release.

For example, `runtime.Store` was added `Aug 30, 2024`, but 0.12 is from 19 July.

If the intent is to use jitpack snapshots, I think this could be mentioned in the readme.

**Comment by andreaTP** [comment]
Hi @abelsromero and thanks a lot for your interest in the project!
You are correct that docs and the latest release are quite different, sorry for that.
We are working hard to polish the public API to be able to release a 1.0.

For 0.0.12 you can refer to the docs at the tag: https://github.com/dylibso/chicory/tree/0.0.12

If you want to add instructions to the docs on how to use Jitpack, please 🙏 go ahead and I'll be happy to merge a PR.

That said, we plan to release a Milestone or RC next week, hopefully the situation will be better after that.

**Comment by abelsromero** [comment]
I'll look forward to the release.

**Comment by andreaTP** [comment]
@abelsromero we released `1.0.0-M1`, I consider this fixed, let me know if something is missing.
