### ISSUE TITLE
Please don't use java.io.File

### ISSUE THREAD

**Issue by mkarg** [dylibso/chicory#661]
The current code base is using the rather obsolete `java.io.File` class in many places, in particular as part of the public API. As the code base uses the modern (and faster, and safer, and correcter) NIO API internally, conversion between `File` and `Path` happens frequently. This makes the code more complex than needed, and it makes runtime slower than needed, as conversion takes considerable time. Also, chicory forces applications to adopt an obsolete API, which is not nice. As typically no existing software will depend on chicory but solely newly written software, this API choice is incomprehensible. All modern software should always use NIO API solely but never need to fall back to `java.io.File`, so it makes no sense to enforce the use of a slow an incorrect API.

Please replace `java.io.File` by `Path` everywhere in your code base. Thanks.

*Disclaimer: [I am a contributor to OpenJDK](https://openjdk.org/census#mkarg). In particular I am working on performance enhancements in the area of IO and NIO. My intention here is to evangelize about modern Java IO.*

**Comment by andreaTP** [comment]
Hi @mkarg and thanks for your interest in the project!

I think it is fine to switch to Path for the public facing API, this means changing the relevant methods in Parser.
Have you spotted any other occurrence exposed to the final user?
Would you be up sending a PR to fix this aspect?

**Comment by mkarg** [comment]
@andreaTP Just hacked in the first changes, see draft #663. It's not done yet, but I am running out of time today. Stay tuned for the rest.

**Comment by andreaTP** [comment]
Thanks! Let me know when it is ready for review, I think it's not critical to change all usages of File, since most things are internal/not exposed, but no strong opinions against either :+1:

**Comment by electrum** [comment]
Do you think we should drop the `File` factory method from `Parser.parse()`?

**Comment by mkarg** [comment]
> Do you think we should drop the `File` factory method from `Parser.parse()`?

+1, as it is most easy for any application to invoke `File.toPath()`, so there is zero benefit from having this variant.

**Comment by mkarg** [comment]
> Since we are still releasing Milestone releases, this is the perfect point in time to remove something from the public API. Please, feel free to include the relevant changes in the PR 👍

I have removed `Parser.parse(File)` today, so the public API and the complete implementation is free of `File` but solely uses `NIO2` instead. `File` is only found in test code. :-)

**Comment by andreaTP** [comment]
After much thinking about this:

- `Parser.parse(File)` is the only place where `File` is directly exposed to the user, it's an overload and people concerned with the usage of `File` can simply avoid using it (plenty of other options)
- There is no evidence of improved security over the current specific and very limited usage
- There is no evidence of improved performance that would impact the user

Given the low value of removing this public API and the lack of fact-based arguments supporting the effort, I decide to discontinue this initiative.
It is consuming substantial time without delivering proportional benefits.

Feel free to open a new issue when additional data becomes available for further discussion.
