### ISSUE TITLE
Please migrate to JDK 21 (LTS)

### ISSUE THREAD

**Issue by mkarg** [dylibso/chicory#662]
Your current code base is targeting JDK 11 (LTS), which was the _pre-predecessor_ of the current LTS release (current is JDK 21, predecessor LTS was 17). By doing so, you are leaving out lots of performance improvements by skipping both, modern APIs, and more importantly, performance-optimized internal changes of OpenJDK. As no old software will make use of chicory but solely newly written software will adopt this pre-1.0 versioned library, you can expect people to be on LTS (21) or pre-LTS (17) already. The design choice to go with obsolete and slow JDK 11 instead is incomprehensible.

Please don't limit performance synthetically by sticking with JDK 11, but consider adopting LTS 17 or even better LTS 21 to get "free" performance improvements, and to get the chance to use new IO APIs.

*Disclaimer: [I am a contributor to OpenJDK](https://openjdk.org/census#mkarg). In particular I am working on performance enhancements in the area of IO and NIO. My intention here is to evangelize about modern Java IO.*

**Comment by andreaTP** [comment]
Hi!

Early in the days of this project we decided to adopt the oldest and most compatible version we could reasonably sustain.
We want maintainers of legacy codebases to be able to use Chicory without forcing a full overhaul of their project.

> As no old software will make use of chicory but solely newly written software will adopt this pre-1.0 versioned library

Would you mind to elaborate? This should be not accurate, otherwise I'm willing to sort the problem and fix it.

That said, I'm open to re-evaluate the Java version after we fix #535 , as this is a blind spot for us.
Any help in that direction is very welcome!

**Comment by mkarg** [comment]
>We want maintainers of **legacy** codebases to be able to use Chicory without forcing a full overhaul of their project.
>>As no old software will make use of chicory but solely newly written software will adopt this pre-1.0 versioned library
>
>Would you mind to elaborate?

Why should an existing *application* (not talking about libs here) written so *long ago that it runs on JDK 11 still* suddenly come up with the need to execute something *such new* as WASM? 🤔 Nobody needs to "overhaul" existing applications to make them run on Java 21 when they are able to run on JDK 11 already. Simply replace the JRE. Again, not talking about libs here.

What use case do you have in mind when it comes to integrating WASM into **legacy** codebases? 🤔

**Comment by andreaTP** [comment]
Hi @mkarg , your is an interesting opinion and I respect it, to read more about the tradeoffs taken in this repo, please, refer to the [coding philosophy](https://github.com/dylibso/chicory/blob/main/CONTRIBUTING.md#coding-philosophy).

Although, we take the argument of performance seriously, so I took the time to run a few benchmarks, and here you have the results:

Compile Java 11 + Run Java 11:

```
Benchmark                                                                                     (fileName)  (input)   Mode  Cnt          Score          Error  Units
BenchmarkFactorialExecution.benchmarkAot                                                             N/A        5  thrpt    5  114248650.246 ± 25080596.714  ops/s
BenchmarkFactorialExecution.benchmarkAot                                                             N/A     1000  thrpt    5    1194450.519 ±   445015.796  ops/s
BenchmarkFactorialExecution.benchmarkInt                                                             N/A        5  thrpt    5    1852545.244 ±   206106.026  ops/s
BenchmarkFactorialExecution.benchmarkInt                                                             N/A     1000  thrpt    5      13299.938 ±     1217.509  ops/s
BenchmarkParsing.benchmark                          wasm-corpus/src/main/resources/compiled/basic.c.wasm      N/A  thrpt    5      23745.181 ±     4578.014  ops/s
BenchmarkParsing.benchmark                wasm-corpus/src/main/resources/compiled/javy-demo.js.javy.wasm      N/A  thrpt    5         18.108 ±        4.381  ops/s
```

Compile Java 11 + Run Java 21:

```
                                                                                    (fileName)  (input)   Mode  Cnt          Score          Error  Units
BenchmarkFactorialExecution.benchmarkAot                                                             N/A        5  thrpt    5  165515759.609 ± 32958223.088  ops/s
BenchmarkFactorialExecution.benchmarkAot                                                             N/A     1000  thrpt    5    1466702.825 ±   215111.391  ops/s
BenchmarkFactorialExecution.benchmarkInt                                                             N/A        5  thrpt    5    2139902.050 ±   104356.682  ops/s
BenchmarkFactorialExecution.benchmarkInt                                                             N/A     1000  thrpt    5      15712.305 ±     3350.937  ops/s
BenchmarkParsing.benchmark                          wasm-corpus/src/main/resources/compiled/basic.c.wasm      N/A  thrpt    5      28858.036 ±      949.458  ops/s
BenchmarkParsing.benchmark                wasm-corpus/src/main/resources/compiled/javy-demo.js.javy.wasm      N/A  thrpt    5         16.999 ±        1.536  ops/s
```

Compile Java 21 + Run Java 21:

```
Benchmark                                                                                     (fileName)  (input)   Mode  Cnt          Score          Error  Units
BenchmarkFactorialExecution.benchmarkAot                                                             N/A        5  thrpt    5  163671917.316 ± 43206076.989  ops/s
BenchmarkFactorialExecution.benchmarkAot                                                             N/A     1000  thrpt    5    1299166.122 ±   364214.734  ops/s
BenchmarkFactorialExecution.benchmarkInt                                                             N/A        5  thrpt    5    1904757.311 ±   288222.027  ops/s
BenchmarkFactorialExecution.benchmarkInt                                                             N/A     1000  thrpt    5      13022.165 ±     1738.512  ops/s
BenchmarkParsing.benchmark                          wasm-corpus/src/main/resources/compiled/basic.c.wasm      N/A  thrpt    5      24802.155 ±    13030.016  ops/s
BenchmarkParsing.benchmark                wasm-corpus/src/main/resources/compiled/javy-demo.js.javy.wasm      N/A  thrpt    5         18.507 ±        4.623  ops/s
```

All in all, there is no gain in **compiling** Chicory with Java 21, but there is a good difference in **running** it on the most modern JVM.
So, please, feel free to run Chicory on Java 21+ to get "free" performance improvements.

Given those results, I'd close this issue, feel free to re-open or open a new one when appropriate!

**Comment by andreaTP** [comment]
Thanks for getting back!

> provides new APIs that you can use for improved performance

Do you mind to share, specifically, what we are missing out in the context of this repository?

**Comment by mkarg** [comment]
Without completely reading your full source code there can only be the general advice to check the full difference between JDK 11 and JDK 21:

APIs: https://javaalmanac.io/jdk/21/apidiff/11/

JEPs: [JDK12](https://openjdk.org/projects/jdk/12) [JDK13](https://openjdk.org/projects/jdk/13) [JDK14](https://openjdk.org/projects/jdk/14) [JDK15](https://openjdk.org/projects/jdk/15) [JDK16](https://openjdk.org/projects/jdk/16) [JDK17](https://openjdk.org/projects/jdk/17) [JDK18](https://openjdk.org/projects/jdk/18) [JDK19](https://openjdk.org/projects/jdk/19) [JDK20](https://openjdk.org/projects/jdk/20) [JDK21](https://openjdk.org/projects/jdk/21)

Whether or not one of these features helps with performance is highly dependend of what your code does *currently* - which I am not aware of. See, this issue is about *opening potential* for performance, not about any specific code line that I already have seen in your code.

Example how I mean this (using JDK 24, hence beyond the scope of this issue): There is `Reader.of(CharSequence)` added which is faster than `new StringReader(String)`. Whether or not this is a benefit is dependent of the code. When `new StringReader(String)` is not used, this improvement plays no role. Hence it's up to the existing code.

Another example: Depending on the actual code it *could* be the case that using "switch expression" + "sealed classes" + "pattern matching" could provide higher performance when compiled for target 21, as the compiler better understands what you intend. Same for massive use of records vs custom de-facto read-only classes. There is no guarantee, but there is *potential*. As Java 11 does not have any of this syntax additions, no such compile-time optimization can happen. Again, there is no guarantee, it is just "opening potential".

**Comment by bhelx** [comment]
I appreciate the interest and the knowledge. WRT to changes to the project, especially ones that take something away, we like to do the cost benefit analysis for the end user. For us to remove Java 11 support (the cost), what do we gain (the benefit)? I disagree that this can't be known. Even a rough test or benchmark should be enough to give us some more information and help make a decision. You should be able to make a fork and try it out. We can demonstrate the benefit on something narrow. If you're not interested in doing that or helping out, that's okay, but we haven't had any users complain about it and I don't think it's an immediate need anyone on the team is going to take on. So, at the moment we're not interested in marginal performance gains, especially hypothetical ones. There's quite a lot to do in terms of documentation, correctness, safety, compatibility, developer experience, etc.

**Comment by mkarg** [comment]
It is your decision and it is pretty fine that you actively decide against my proposal. I only try to trigger open source projects to not "by default" stick with outdated versions but to actively consider the possibilities *they give up (even just potentially)*. Often performance is not improved, sometimes just marginally, but sometimes my tips / PRs lead to 1200x improved performance (happened recently). I see that you are not interested in checking that on your own, which is absolutely ok for me.

**Comment by yigit** [comment]
For Android, anything above 11 will be limited.

You can find the documentation on it [here](https://developer.android.com/build/jdks#compileSdk):

Some 11+ APIs are supported via [desugaring](https://developer.android.com/studio/write/java11-default-support-table) but it is hard to know which ones are safe to use without running your test suite on android (and i think you'll also need to compile with the Android Gradle Plugin to get desugaring support).
