### ISSUE TITLE
Version not replaced in docs

### ISSUE THREAD

**Issue by electrum** [dylibso/chicory#669]
These pages show `DOCS_PLACEHOLDER_VERSION`:

https://chicory.dev/docs/
https://chicory.dev/docs/usage/host-functions

**Comment by andreaTP** [comment]
Right, we need to do a "proper release" of the docs and figure out how to do it following this:
https://docusaurus.io/docs/versioning

**Comment by andreaTP** [comment]
Fixed in #679 by removing references to versions in the docs, docusaurus clearly suggests that we freeze documentation at a specific version rarely.
Probably we are going to do it once for 1.0.0, but not before.
