### ISSUE TITLE
WASM data segment content outputted when printing a guest-allocated String

### ISSUE THREAD

**Issue by fearnoeval** [dylibso/chicory#671]
I created a repo with steps to reproduce and more detail at [fearnoeval/chicory-error](https://github.com/fearnoeval/chicory-error). The most relevant files there are likely:
- [The Rust source file](https://github.com/fearnoeval/chicory-error/blob/cd24fd65b9db5dbbc0c049349cd87010fc8ba7f0/chicory-error-rs/src/lib.rs)
- [The Java source file](https://github.com/fearnoeval/chicory-error/blob/cd24fd65b9db5dbbc0c049349cd87010fc8ba7f0/chicory-error-java/src/main/java/io/github/fearnoeval/chicoryerrorjava/Main.java)

The gist is that I have some Rust code that gets a reference to a static `Hello, World!` string, reverses it, `collect`s it into a `String` (incurring an allocation), gets a reference to the backing byte array, and calls the host's `console.log` function from [the example in the docs](https://chicory.dev/docs/usage/host-functions). The output is not as expected, though, and includes contents from the WASM binary's data segment as well as most or all of the reversed string (I did not investigate if the expected `!d` is in the replacement character preceding `lroW ,olleH`):

```
library/std/src/alloc.rsbes faillibrary/std/src/panicking.rs,�n failed: psize >= size + min_overhead()� assertion failed: psize <= size + max_overhead()�



capacity overflow�library/alloc/src/raw_vec.rs�called `Option::unwrap()` on a `None` value00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899������������������������

                                                                                        $$,,44<<DDLLTT\\ddlltt||���������� �lroW ,olleH
```

Since [the count_vowels example simply allocates a `Vec` without ceremony](https://github.com/dylibso/chicory/blob/1a0ee7429b683014b1bc12c01c7d485498919b0c/wasm-corpus/src/main/resources/rust/count_vowels.rs#L7-L19), I assumed that I'd similarly be able to allocate memory for a `String`. I'll note that compared to the `count_vowels` example, I'm not "forgetting" and "remembering" the memory since the host never takes ownership of it, so I didn't expect that to have any meaningful impact.

Am I doing something incorrectly, or is this a bug? Thanks!

**Comment by evacchi** [comment]
humm I am not 100% sure of how Rust allocates Strings, but you might be getting indices that are not really pointing into the linear memory. Are you sure the String is heap-allocated? especially when it's 'static

**Comment by fearnoeval** [comment]
> Are you sure the String is heap-allocated?

Yes, in Rust, [the `String` type is heap-allocated](https://doc.rust-lang.org/std/string/struct.String.html)

> especially when it's 'static

The `String` is not static, the original string is (`&'static str` in Rust types). Reversing the original and "collecting" it into a `String` causes the allocation

**Comment by bhelx** [comment]
I'd be really curious what this is giving you as a pointer: https://github.com/fearnoeval/chicory-error/blob/main/chicory-error-rs/src/lib.rs#L12

as @evacchi noted, the memory that the host has access to is heap memory. &str is not heap memory. i think in wasm it gets put in the data section.

**Comment by bhelx** [comment]
When compiling and checking the data section:

```
wasm-objdump target/wasm32-unknown-unknown/debug/example.wasm --section=Data -x | grep Hell
  - 0100420: 6170 4865 6c6c 6f2c 2057 6f72 6c64 2100  apHello, World!.
```

**Comment by fearnoeval** [comment]
@bhelx
> I'd be really curious what this is giving you as a pointer: https://github.com/fearnoeval/chicory-error/blob/main/chicory-error-rs/src/lib.rs#L12 

[The code you linked to](https://github.com/fearnoeval/chicory-error/blob/main/chicory-error-rs/src/lib.rs#L12) works as expected and is there to show that the original code from the docs does indeed work before I started trying something different. You can see [the full output with the succeeding "Hello World!" loop output on the README](https://github.com/fearnoeval/chicory-error/blob/cd24fd65b9db5dbbc0c049349cd87010fc8ba7f0/README.md). I modified the Java and logged both len and offset and see this for every iteration:
```
len: 1048576, offset: 13
```
Since you probably actually wanted the output of the function that is misbehaving, this is what I see for that one:
```
len: 1114120, offset: 13
```

> as @evacchi noted, the memory that the host has access to is heap memory. &'static str is not heap memory. i think in wasm it gets put in the data section.

I know that the `&'static str` is not heap memory, which I seem to be failing to convey, so here's the breakdown:
- [The static string](https://github.com/fearnoeval/chicory-error/blob/cd24fd65b9db5dbbc0c049349cd87010fc8ba7f0/chicory-error-rs/src/lib.rs#L26)
- [The static string (`&'static str`) being used to create a reversed version of itself as a `String` (heap-allocated)](https://github.com/fearnoeval/chicory-error/blob/cd24fd65b9db5dbbc0c049349cd87010fc8ba7f0/chicory-error-rs/src/lib.rs#L26)

> I'd maybe try turning it into a heap string:

It is already as mentioned in the previous blurb.

> probably what you don't want is to allocate each time, but i'm unsure what the end goal is

For right now, allocating every time is exactly what I want since I'm trying to show a minimum failing case.

**Comment by andreaTP** [comment]
Took a quick look and I can reproduce locally, seems like an issue with the Rust code and @bhelx might know the solution on top of he's head.

I can remember myself struggling with this aspect of Rust and I ended up [cycling on the bytes](https://github.com/andreaTP/kroxylicious-wasm/blob/690e39562effbcf6c5edffebde6969de391c3ec7/src/main/resources/rust/fromto.rs#L19-L31).

**Comment by fearnoeval** [comment]
[I got it to work with no changes to the Rust code](https://github.com/fearnoeval/chicory-error/commit/9e6e09322074f426a44e9ecb5a87492b85ca95cd), so everything was kosher memory-wise, but I had the address and length in the wrong order. The fix could have occurred on either side, but pointer-first is far more common in my experience when dealing with fat pointers, so I fixed it on the Java side.

I didn't go so far as seeing how the example version has the expected output with either argument order, though there's a significant difference in performance (lots of null bytes printing with no visible output?). Regardless, things seem to be working now. Thanks!

**Comment by andreaTP** [comment]
Argh, @fearnoeval I wasted so much time for such a small bug :sweat_smile: 

Fixed in https://github.com/fearnoeval/chicory-error/pull/1

And it gives the expected output:

```
java -jar target/chickory-error-java-0.0.1-SNAPSHOT.jar
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
!dlroW ,olleH
```

**Comment by andreaTP** [comment]
Closing as complete :rocket: 

I think the docs are consistent as they refer to this `wat`: https://github.com/dylibso/chicory/blob/3cef4f59b48266f5b84c8ecfaac2a350d6dd29c8/wasm-corpus/src/main/resources/wat/host-function.wat#L15-L16

where the order is `len`, `offset`.
