### ISSUE TITLE
Support WASI P2

### ISSUE THREAD

**Issue by superchris** [dylibso/chicory#673]
I noticed support for WASI is P1 now, but P2 has been out for a little while now. It would be awesome to have support for P2 and the component model!

**Comment by bhelx** [comment]
wasip2 support is a pretty big lift and doesn't seem to be getting adopted much outside the wasmtime ecosystem yet, but we're happy to support anyone here who wants to give it a shot. Though, I'd prefer to focus current efforts on ironing out wasip1 as all the runtimes and most the compiler toolchains support it. I think the component model would require even more work on top of that and still seems like it's going to even longer until the ecosystem catches up.

**Comment by andreaTP** [comment]
WASI Preview 2 requires the runtime to support the [component model proposal](https://github.com/WebAssembly/component-model) which is currently Phase 1.
This means it will likely change a lot between now and its final shape, more often than not these larger proposals like Wasm GC, EH etc..

I added a little section to `CONTRIBUTING.md` to settle expectations in this direction.

That said, @superchris , thanks a lot for the question and the interest in the project!
We encourage anyone to explore the boundaries, keep in touch with us on the Zulip channel.
